import { readEvidence, mergeEvidence } from "./session-evidence";
import { enabled } from "../profile";
import { open, readdir, readFile, stat } from "node:fs/promises";
import { homedir } from "node:os";
import { join } from "node:path";
import { type Cause, Clock, Deferred, Duration, Effect, Option, Schema, Struct } from "effect";
import { addRefs, countRefs } from "@/lib/refs";
import { Store, storeKey } from "@/services/store";
import { conversation } from "./session-conversation";
import { codexRunning } from "./session-activity";
import { SessionContextUsage } from "@mondash/shared/contract";
import { sessionContext } from "./session-context";
import { readAttachment, type AttachmentSource } from "./session-attachments";
import { sessionPreview } from "./session-preview";
import { workspaceFiles } from "./session-files";
import { linkedPRRefs } from "./session-links";
import { readCodexThreads } from "./codex-threads";
import { expandClaudeFiles, mergeClaudeContinuations } from "./claude-archives";

const RefCounts = Schema.Record(Schema.String, Schema.Finite);

export const AgentSession = Schema.Struct({
  tool: Schema.Literals(["claude", "codex"]),
  id: Schema.String,
  title: Schema.String,
  /** Your first prompt: it usually says what the session is for. */
  firstPrompt: Schema.String,
  /** Generated by Claude when compacting: candidate context, never a user prompt. */
  contextSummary: Schema.optional(Schema.String),
  /** Native Claude conversation identity shared by its continuation transcripts. */
  conversationId: Schema.optional(Schema.String),
  lastPrompt: Schema.String,
  preview: Schema.optional(Schema.String),
  previewKind: Schema.optional(Schema.Literals(["recap", "response"])),
  cwd: Schema.String,
  branch: Schema.optional(Schema.String),
  /** Ticket IDs, PR links, Slack threads and Notion pages in the messages, with how often each appears. */
  refs: RefCounts,
  /** The same, in the prompts you typed only: what you asked about, not what tools printed. */
  promptRefs: RefCounts,
  /** Explicit PR associations recorded by the agent, not incidental transcript mentions. */
  linkedPRs: Schema.optional(Schema.Array(Schema.String)),
  /** Archived (or ended) on claude.ai, and not continued since. */
  archived: Schema.optional(Schema.Boolean),
  running: Schema.optional(Schema.Boolean),
  contextUsage: Schema.optional(SessionContextUsage),
  updatedAt: Schema.Date,
});
export type AgentSession = typeof AgentSession.Type;

export const RECENT_KEY = storeKey("sessions:recent:v6", Schema.Array(AgentSession));
// Local files, read again every 30 s by live.ts.
export const RECENT_FRESH = Duration.seconds(30);

const DAY = 24 * 60 * 60 * 1000;
// "Other recent agent sessions" shows the last week.
// ponytail: fixed look-back; make it "since you last opened the dashboard" if a week is too much or too little.
const RECENT_DAYS = 7;
// Tickets and Scoping cards last for weeks, so their sessions are searched further back.
const MENTION_DAYS = 90;

const lines = (text: string) =>
  text.split("\n").flatMap((line): unknown[] => {
    try {
      return [JSON.parse(line)];
    } catch {
      return [];
    }
  });

const loose = <S extends Schema.StructWithRest.Objects>(schema: S) =>
  Schema.StructWithRest(schema, [Schema.Record(Schema.String, Schema.Unknown)]);
const ContentPart = loose(Schema.Struct({ type: Schema.String, text: Schema.optional(Schema.String) }));
const ClaudeLine = loose(
  Schema.Struct({
    type: Schema.String,
    isCompactSummary: Schema.optional(Schema.Boolean),
    aiTitle: Schema.optional(Schema.String),
    // The session's name as the Claude app shows it: set by --name, /rename or Claude itself.
    customTitle: Schema.optional(Schema.String),
    agentName: Schema.optional(Schema.String),
    lastPrompt: Schema.optional(Schema.String),
    cwd: Schema.optional(Schema.String),
    gitBranch: Schema.optional(Schema.String),
    timestamp: Schema.optional(Schema.String),
    content: Schema.optional(Schema.Unknown),
    message: Schema.optional(
      loose(Schema.Struct({ content: Schema.Union([Schema.String, Schema.Array(ContentPart)]) })),
    ),
  }),
);
const decodeClaudeLine = Schema.decodeUnknownOption(ClaudeLine);

/** Provider-injected repository instructions are not evidence of the work requested in a session. */
const injectedInstructions = (text: string) =>
  /^(?:# AGENTS\.md instructions for\b|<INSTRUCTIONS>|<user_instructions>)/i.test(text.trim());

function withoutInstructions<T extends { type: string; text?: string }>(content: readonly T[]): T[];
function withoutInstructions<T extends { type: string; text?: string }>(content: string | readonly T[]): string | T[];
function withoutInstructions<T extends { type: string; text?: string }>(content: string | readonly T[]) {
  return typeof content === "string"
    ? injectedInstructions(content)
      ? ""
      : content
    : content.filter((part) => !part.text || !injectedInstructions(part.text));
}

/** The typed text of a user message. Tool results and injected "<...>" blocks are not typed by you. */
function typedText(content: string | readonly { type: string; text?: string }[]): string {
  content = withoutInstructions(content);
  const text =
    typeof content === "string" ? content : content.map((c) => (c.type === "text" && c.text ? c.text : "")).join("");
  return text.trim().startsWith("<") ? "" : text.trim();
}

/** What one log file says. A Claude file is a whole session; a long Codex session is split across files. */
const Part = Schema.Struct({
  ...Struct.omit(AgentSession.fields, ["updatedAt"]),
  lastAt: Schema.Finite,
  previewAt: Schema.optional(Schema.Finite),
  contextAt: Schema.optional(Schema.Finite),
});
type Part = typeof Part.Type;

/**
 * A file's summary as saved in the store, with the size and time it was read at. A restart then reads only the files
 * that changed, not 90 days of transcripts (about 5 GB).
 */
const savedPart = (file: string) =>
  storeKey(
    // Reparse summaries that included injected instructions in prompts and reference counts.
    `session-file:${file.includes("/.codex/") ? "v4" : "v6"}:${file}`,
    Schema.Struct({ size: Schema.Finite, mtimeMs: Schema.Finite, part: Schema.NullOr(Part) }),
  );

function parseClaude(text: string, file: string): Part | undefined {
  const records = lines(text);
  let title = "";
  let name = "";
  let firstPrompt = "";
  let contextSummary: string | undefined;
  let lastPrompt = "";
  let cwd = "";
  let branch: string | undefined;
  let lastAt = 0;
  // Messages only: cwd and gitBranch repeat on every line, so counting them would inflate the folder's ticket.
  const messages: string[] = [];
  const prompts: string[] = [];
  for (const raw of records) {
    const line = decodeClaudeLine(raw);
    if (Option.isNone(line)) continue;
    const l = line.value;
    if (l.aiTitle) title = l.aiTitle;
    if (l.customTitle) name = l.customTitle;
    else if (l.agentName && !name) name = l.agentName;
    const text = l.type === "user" && l.message ? typedText(l.message.content) : "";
    const summary =
      l.isCompactSummary || text.startsWith("This session is being continued from a previous conversation");
    if (summary && text) contextSummary = text;
    const typed = summary ? "" : text;
    if (typed) prompts.push(typed);
    if (!firstPrompt) firstPrompt = typed;
    if (l.lastPrompt && typedText(l.lastPrompt)) lastPrompt = typedText(l.lastPrompt);
    if (l.message) messages.push(JSON.stringify({ ...l.message, content: withoutInstructions(l.message.content) }));
    if (l.cwd) cwd = l.cwd;
    if (l.gitBranch && l.gitBranch !== "HEAD") branch = l.gitBranch;
    if (l.timestamp) lastAt = Math.max(lastAt, Date.parse(l.timestamp));
  }
  if (!lastPrompt || !cwd) return undefined;
  const id = file.slice(file.lastIndexOf("/") + 1, -".jsonl".length);
  return {
    tool: "claude",
    id,
    title: name || title || lastPrompt,
    firstPrompt: firstPrompt || lastPrompt,
    contextSummary,
    lastPrompt,
    cwd,
    branch,
    refs: countRefs(messages.join("\n")),
    promptRefs: countRefs(prompts.join("\n")),
    linkedPRs: linkedPRRefs(records, id),
    lastAt,
    ...sessionPreview("claude", records),
    ...sessionContext("claude", records),
  };
}

const CodexMeta = Schema.Struct({
  type: Schema.Literal("session_meta"),
  payload: Schema.Struct({ id: Schema.String, cwd: Schema.String, thread_source: Schema.optional(Schema.String) }),
});
const CodexMessage = Schema.Struct({
  type: Schema.Literal("response_item"),
  payload: Schema.Struct({
    type: Schema.Literal("message"),
    role: Schema.String,
    content: Schema.Array(ContentPart),
  }),
});
const Timestamped = loose(Schema.Struct({ timestamp: Schema.String }));
const CodexItem = loose(Schema.Struct({ type: Schema.String, payload: Schema.Unknown }));
const CodexIndexLine = Schema.Struct({ id: Schema.String, thread_name: Schema.String });
const decodeCodexMeta = Schema.decodeUnknownOption(CodexMeta);
const decodeCodexMessage = Schema.decodeUnknownOption(CodexMessage);
const decodeCodexUserEvent = Schema.decodeUnknownOption(
  Schema.Struct({
    type: Schema.Literal("event_msg"),
    payload: Schema.Struct({ type: Schema.Literal("user_message"), message: Schema.String }),
  }),
);
const decodeTimestamped = Schema.decodeUnknownOption(Timestamped);
const decodeCodexItem = Schema.decodeUnknownOption(CodexItem);
const decodeCodexIndexLine = Schema.decodeUnknownOption(CodexIndexLine);
const isSessionId = Schema.is(Schema.String.check(Schema.isUUID()));

function parseCodex(text: string): Part | undefined {
  const records = lines(text);
  let id = "";
  let cwd = "";
  let firstPrompt = "";
  let lastPrompt = "";
  let lastAt = 0;
  const messages: string[] = [];
  const prompts: string[] = [];
  for (const raw of records) {
    const meta = decodeCodexMeta(raw);
    if (Option.isSome(meta)) {
      // A sub-agent's work is part of its parent session, which is listed; a sub-agent cannot be resumed on its own.
      if (meta.value.payload.thread_source === "subagent") return undefined;
      ({ id, cwd } = meta.value.payload);
      continue;
    }
    const stamped = decodeTimestamped(raw);
    if (Option.isSome(stamped)) lastAt = Math.max(lastAt, Date.parse(stamped.value.timestamp));
    const message = decodeCodexMessage(raw);
    if (Option.isSome(message)) {
      const { payload } = message.value;
      // System/developer messages and repository instruction parts are provider context, not work evidence.
      if (payload.role !== "user" && payload.role !== "assistant") continue;
      const content = withoutInstructions(payload.content);
      messages.push(JSON.stringify({ ...payload, content }));
      if (payload.role !== "user") continue;
      const typed = content
        .map((c) => c.text)
        .join("")
        .trim();
      if (!typed || typed.startsWith("<")) continue;
      if (!firstPrompt) firstPrompt = typed;
      lastPrompt = typed;
      prompts.push(typed);
      continue;
    }
    // Codex can also mirror a user message as an event; do not count an injected copy there either.
    const event = decodeCodexUserEvent(raw);
    if (Option.isSome(event) && injectedInstructions(event.value.payload.message)) continue;
    // Tool results remain reference evidence; turn_context repeats injected instructions and the folder.
    const item = decodeCodexItem(raw);
    if (Option.isSome(item) && item.value.type !== "turn_context") messages.push(JSON.stringify(item.value.payload));
  }
  if (!id) return undefined;
  return {
    tool: "codex",
    id,
    title: "",
    firstPrompt,
    lastPrompt,
    cwd,
    refs: countRefs(messages.join("\n")),
    promptRefs: countRefs(prompts.join("\n")),
    lastAt,
    running: codexRunning(records),
    ...sessionPreview("codex", records),
    ...sessionContext("codex", records),
  };
}

// Each file's summary, kept between page loads. Only files that changed (size or time) are read again: old sessions never do.
// ponytail: a module-level memo of parsed files, lost on restart; the Store holds the result that matters.
const fileCache = new Map<string, { size: number; mtimeMs: number; parsedAt: number; part: Part | undefined }>();
// One read per file at a time: Resume and the Roadmap ask for the same active transcript together.
const parsing = new Map<string, Deferred.Deferred<Part | undefined, Cause.UnknownError>>();
// ponytail: an active transcript (tens of MB) is parsed whole and synchronously, so a changed file is parsed again at
// most once a minute and its older summary stands in until then; parse only the appended tail if that is too stale.
const REPARSE_AFTER = 60_000;

const fileStat = (file: string) => Effect.tryPromise(() => stat(file));
/** Refresh lifecycle markers without reparsing a multi-megabyte active transcript. */
const runningTail = (file: string, fallback?: boolean) =>
  Effect.tryPromise(async () => {
    const handle = await open(file, "r");
    try {
      const { size } = await handle.stat();
      const start = Math.max(0, size - 256 * 1024);
      const buffer = Buffer.alloc(size - start);
      const { bytesRead } = await handle.read(buffer, 0, buffer.length, start);
      const tail = buffer.subarray(0, bytesRead).toString("utf8");
      return codexRunning(lines(start ? tail.slice(tail.indexOf("\n") + 1) : tail), fallback);
    } finally {
      await handle.close();
    }
  }).pipe(Effect.orElseSucceed(() => fallback));

const readText = (file: string) => Effect.tryPromise((signal) => readFile(file, { encoding: "utf8", signal }));
const readDir = (dir: string) => Effect.tryPromise(() => readdir(dir)).pipe(Effect.orElseSucceed((): string[] => []));
const codexThreads = () => readCodexThreads(join(homedir(), ".codex", "state_5.sqlite"));

const parse = (file: string, size: number, mtimeMs: number) =>
  Effect.gen(function* () {
    const store = yield* Effect.serviceOption(Store);
    const key = savedPart(file);
    const saved = Option.isSome(store)
      ? yield* store.value.read(key).pipe(Effect.orElseSucceed(() => undefined))
      : undefined;
    const kept = saved && saved.value.size === size && saved.value.mtimeMs === mtimeMs ? saved.value : undefined;
    const text = kept ? "" : yield* readText(file);
    const parsed: Part | undefined = kept
      ? kept.part === null
        ? undefined
        : kept.part
      : file.includes("/.codex/")
        ? parseCodex(text)
        : parseClaude(text, file);
    if (!kept && Option.isSome(store))
      yield* store.value
        .write(key, { size, mtimeMs, part: parsed === undefined ? null : parsed })
        .pipe(Effect.catch((failure) => Effect.logWarning(`Could not save the summary of ${file}`, failure)));
    fileCache.set(file, { size, mtimeMs, parsedAt: yield* Clock.currentTimeMillis, part: parsed });
    return parsed;
  });

/** What one log file says, from the memo while it holds. */
export const part = (file: string) =>
  Effect.gen(function* () {
    const { size, mtimeMs } = yield* fileStat(file);
    const hit = fileCache.get(file);
    const now = yield* Clock.currentTimeMillis;
    if (hit && hit.size === size && hit.mtimeMs === mtimeMs) return hit.part;
    if (hit && now - hit.parsedAt < REPARSE_AFTER) {
      if (hit.part?.tool !== "codex") return hit.part;
      return { ...hit.part, running: yield* runningTail(file, hit.part.running) };
    }
    const running = parsing.get(file);
    if (running) return yield* Deferred.await(running);
    const done = Deferred.makeUnsafe<Part | undefined, Cause.UnknownError>();
    parsing.set(file, done);
    // Detached, so a caller that stops waiting does not leave the others waiting on a parse that never ends.
    yield* Effect.forkDetach(
      parse(file, size, mtimeMs).pipe(
        Effect.exit,
        Effect.flatMap((exit) => Deferred.done(done, exit)),
        Effect.ensuring(Effect.sync(() => parsing.delete(file))),
      ),
    );
    return yield* Deferred.await(done);
  });

/** Filename inventory only; old transcripts are read only when a nominated continuation needs their context. */
const claudeFiles = Effect.gen(function* () {
  const claudeRoot = join(homedir(), ".claude", "projects");
  const projects = yield* readDir(claudeRoot);
  return (yield* Effect.forEach(
    projects,
    (p) =>
      readDir(join(claudeRoot, p)).pipe(
        Effect.map((files) => files.filter((f) => f.endsWith(".jsonl")).map((f) => join(claudeRoot, p, f))),
      ),
    { concurrency: "unbounded" },
  )).flat();
});

/** Log files changed in the last `days` days. Codex files sit in year/month/day folders. */
const logFiles = (days: number) =>
  Effect.gen(function* () {
    const now = yield* Clock.currentTimeMillis;
    const after = now - days * DAY;
    const recentClaude = (yield* Effect.forEach(
      yield* claudeFiles,
      (f) => fileStat(f).pipe(Effect.map((s) => (s.mtimeMs >= after ? [f] : []))),
      { concurrency: 32 },
    )).flat();
    const codexRoot = join(homedir(), ".codex", "sessions");
    const dayDirs = Array.from({ length: days + 1 }, (_, i) => {
      const d = new Date(now - i * DAY);
      return join(
        codexRoot,
        String(d.getFullYear()),
        String(d.getMonth() + 1).padStart(2, "0"),
        String(d.getDate()).padStart(2, "0"),
      );
    });
    const codex = (yield* Effect.forEach(
      dayDirs,
      (dir) => readDir(dir).pipe(Effect.map((files) => files.map((f) => join(dir, f)))),
      { concurrency: "unbounded" },
    )).flat();
    const archiveDir = join(homedir(), ".codex", "archived_sessions");
    const archived = (yield* Effect.forEach(
      (yield* readDir(archiveDir)).filter((f) => f.endsWith(".jsonl")),
      (f) => {
        const path = join(archiveDir, f);
        return fileStat(path).pipe(
          Effect.map((s) => (s.mtimeMs >= after ? [path] : [])),
          Effect.orElseSucceed(() => []),
        );
      },
      { concurrency: 32 },
    )).flat();
    const indexed = (yield* codexThreads())
      .filter((thread) => thread.updated_at * 1000 >= after)
      .map((thread) => thread.rollout_path);
    return [...new Set([...recentClaude, ...codex, ...archived, ...indexed])];
  });

const codexNames = Effect.gen(function* () {
  const names = new Map<string, string>();
  const index = yield* readText(join(homedir(), ".codex", "session_index.jsonl")).pipe(Effect.orElseSucceed(() => ""));
  for (const raw of lines(index)) {
    const line = decodeCodexIndexLine(raw);
    if (Option.isSome(line)) names.set(line.value.id, line.value.thread_name);
  }
  return names;
});

/** Sessions from these files, active since `after`, newest first. A Codex session's files are merged, oldest first. */
export const sessionsFrom = (files: ReadonlyArray<string>, after: number, nativeRoot?: string) =>
  Effect.gen(function* () {
    const [parts, names, threads] = yield* Effect.all(
      [
        Effect.forEach(
          files.toSorted(),
          (file) =>
            part(file).pipe(
              Effect.map((p) => (p && file.includes("/.codex/archived_sessions/") ? { ...p, archived: true } : p)),
              Effect.orElseSucceed(() => undefined),
            ),
          { concurrency: 2 },
        ),
        codexNames,
        codexThreads(),
      ],
      {
        concurrency: "unbounded",
      },
    );
    const archives = new Map(threads.map((thread) => [thread.id, thread.archived !== 0]));
    const byId = new Map<string, Part>();
    for (const p of parts) {
      if (!p) continue;
      const prev = byId.get(p.id);
      byId.set(
        p.id,
        prev
          ? {
              ...prev,
              firstPrompt: prev.firstPrompt ? prev.firstPrompt : p.firstPrompt,
              lastPrompt: p.lastPrompt ? p.lastPrompt : prev.lastPrompt,
              lastAt: Math.max(prev.lastAt, p.lastAt),
              ...(p.running !== undefined && p.lastAt >= prev.lastAt ? { running: p.running } : {}),
              ...(p.contextAt !== undefined && p.contextAt >= (prev.contextAt ?? 0)
                ? { contextUsage: p.contextUsage, contextAt: p.contextAt }
                : {}),
              ...(p.preview && (p.previewAt ?? 0) >= (prev.previewAt ?? 0)
                ? { preview: p.preview, previewKind: p.previewKind, previewAt: p.previewAt }
                : {}),
              refs: addRefs(prev.refs, p.refs),
              promptRefs: addRefs(prev.promptRefs, p.promptRefs),
              linkedPRs: [...new Set([...(prev.linkedPRs ?? []), ...(p.linkedPRs ?? [])])],
            }
          : p,
      );
    }
    const merged = yield* mergeClaudeContinuations(
      [...byId.values()]
        // The file time is not reliable (tools touch old files), so use the last message time.
        .filter((p) => p.lastPrompt)
        .map(
          ({
            lastAt,
            previewAt: _previewAt,
            contextAt: _contextAt,
            archived: transcriptArchived,
            ...p
          }): AgentSession => {
            void _previewAt; // Only used while merging transcript parts; it is not session metadata.
            void _contextAt;
            const name = p.tool === "codex" ? names.get(p.id) : undefined;
            return {
              ...p,
              ...(p.tool === "codex" && archives.has(p.id)
                ? { archived: archives.get(p.id) }
                : transcriptArchived === undefined
                  ? {}
                  : { archived: transcriptArchived }),
              title: name ? name : p.title ? p.title : p.lastPrompt,
              updatedAt: new Date(lastAt),
            };
          },
        )
        .toSorted((a, b) => b.updatedAt.getTime() - a.updatedAt.getTime()),
      nativeRoot,
    );
    return merged.filter((session) => session.updatedAt.getTime() >= after);
  });

const recentSessions = Effect.gen(function* () {
  const files = yield* logFiles(RECENT_DAYS);
  const now = yield* Clock.currentTimeMillis;
  return yield* sessionsFrom(yield* expandClaudeFiles(files, yield* claudeFiles), now - RECENT_DAYS * DAY);
});

/** Claude Code and Codex sessions active in the last week, newest first, as live.ts last read them. */
export const getRecentSessions = Effect.fn("sessions.getRecentSessions")(function* () {
  if (!enabled("sessions")) return [];
  return yield* (yield* Store).cached(RECENT_KEY, Duration.infinity, recentSessions);
});

/** Reads the sessions again now, for the live check. */
export const rebuildRecentSessions = Effect.fn("sessions.rebuildRecentSessions")(function* () {
  if (!enabled("sessions")) return [];
  return yield* (yield* Store).refresh(RECENT_KEY, recentSessions);
});

/** A session's transcript files from the last 90 days, oldest first. The id is checked, so it cannot name a path. */
const sessionFiles = (id: string) =>
  isSessionId(id)
    ? logFiles(MENTION_DAYS).pipe(
        Effect.map((files) => files.filter((file) => file.endsWith(`${id}.jsonl`)).toSorted()),
      )
    : Effect.succeed<ReadonlyArray<string>>([]);

const findSession = (files: ReadonlyArray<string>, id: string) =>
  Effect.gen(function* () {
    const now = yield* Clock.currentTimeMillis;
    return (yield* sessionsFrom(files, now - MENTION_DAYS * DAY)).find((session) => session.id === id);
  });

/** Resolve an existing indexed transcript without accepting a caller-supplied path. */
export const getLocalSession = Effect.fn("sessions.getLocalSession")(function* (id: string) {
  return yield* findSession(yield* sessionFiles(id), id);
});

/** All native continuation references for this nominated session, including history outside the recent-session window. */
export const getSessionWithContinuations = Effect.fn("sessions.getSessionWithContinuations")(function* (
  session: AgentSession,
) {
  if (session.tool !== "claude") return session;
  const files = yield* expandClaudeFiles(yield* sessionFiles(session.id), yield* claudeFiles);
  const combined = yield* sessionsFrom(files, 0);
  return (
    combined.find(
      (candidate) =>
        candidate.tool === session.tool &&
        (candidate.id === session.id ||
          (session.conversationId !== undefined && candidate.conversationId === session.conversationId)),
    ) ?? session
  );
});

/** Evidence inventory is local and shared; native Claude aliases include older continuation transcripts. */
export const getSessionMatchEvidence = Effect.fn("sessions.getSessionMatchEvidence")(function* (session: AgentSession) {
  if (!isSessionId(session.id)) return [];
  const store = yield* Store;
  const available = yield* store.cached(
    storeKey("session-evidence-files:v1", Schema.Array(Schema.String)),
    Duration.seconds(30),
    logFiles(MENTION_DAYS),
  );
  const nominated = available.filter((file) => file.endsWith(`${session.id}.jsonl`));
  const files = session.tool === "claude" ? yield* expandClaudeFiles(nominated, yield* claudeFiles) : nominated;
  return mergeEvidence(yield* Effect.forEach(files, (file) => readEvidence(file, session.tool), { concurrency: 2 }));
});

type LoadedConversation = {
  session: AgentSession;
  turns: ReturnType<typeof conversation>["turns"];
  truncated: boolean;
  running: boolean | undefined;
  sources: Map<string, AttachmentSource>;
};
// A bounded cache shared by message polls and attachment reads; changed file stats invalidate it immediately.
const conversations = new Map<string, { signature: string; value: LoadedConversation }>();
const conversationRecords = Effect.fn("sessions.conversationRecords")(function* (tool: "claude" | "codex", id: string) {
  const files = yield* sessionFiles(id);
  const stats = yield* Effect.forEach(files, fileStat, { concurrency: 2 });
  const signature = JSON.stringify(files.map((file, index) => [file, stats[index]!.size, stats[index]!.mtimeMs]));
  const key = `${tool}:${id}`;
  const cached = conversations.get(key);
  if (cached?.signature === signature) return cached.value;
  const session = yield* findSession(files, id);
  if (!session || session.tool !== tool) return undefined;
  const texts = yield* Effect.forEach(files, readText, { concurrency: 2 });
  const records = texts.flatMap(lines);
  const sources = new Map<string, AttachmentSource>();
  const value: LoadedConversation = {
    session,
    ...conversation(tool, records, sources),
    running: tool === "codex" ? codexRunning(records) : undefined,
    sources,
  };
  const visible = new Set(
    value.turns.flatMap((turn) => [
      ...(turn.attachments?.map((attachment) => attachment.id) ?? []),
      ...(turn.edits?.map((edit) => edit.file.id) ?? []),
    ]),
  );
  for (const attachmentId of sources.keys()) if (!visible.has(attachmentId)) sources.delete(attachmentId);
  // Attachment bytes only need a cache while that session is being viewed.
  conversations.delete(key);
  conversations.set(key, { signature, value });
  if (conversations.size > 2) conversations.delete(conversations.keys().next().value!);
  return value;
});

/** Read the transcript now, including progress that arrived after the session summary. */
export const getLocalConversation = Effect.fn("sessions.getLocalConversation")(function* (
  tool: "claude" | "codex",
  id: string,
) {
  const found = yield* conversationRecords(tool, id);
  if (!found) return undefined;
  return { session: found.session, turns: found.turns, truncated: found.truncated, running: found.running };
});

/** Resolve the opaque attachment id against this session's own transcript. */
export const getLocalAttachment = Effect.fn("sessions.getLocalAttachment")(function* (
  tool: "claude" | "codex",
  id: string,
  attachmentId: string,
) {
  const found = yield* conversationRecords(tool, id);
  if (!found) return undefined;
  const source =
    found.sources.get(attachmentId) ??
    (yield* Effect.tryPromise(() => workspaceFiles(found.session.cwd))).sources.get(attachmentId);
  return source ? yield* Effect.tryPromise(() => readAttachment(source)) : undefined;
});

export const getLocalFiles = Effect.fn("sessions.getLocalFiles")(function* (tool: "claude" | "codex", id: string) {
  const found = yield* conversationRecords(tool, id);
  if (!found) return undefined;
  const workspace = yield* Effect.tryPromise(() => workspaceFiles(found.session.cwd));
  return {
    root: workspace.root,
    files: [...workspace.sources.values()].map((source) => source.attachment),
    truncated: workspace.truncated,
  };
});

/**
 * Sessions from the last 90 days that mention any of these references (ticket IDs, PR links, Slack threads, Notion pages),
 * plus the last week's sessions. Each file's references come from its saved summary, so only changed files are read.
 */
export const getSessionsMentioning = Effect.fn("sessions.getSessionsMentioning")(function* (
  refKeys: ReadonlyArray<string>,
) {
  if (!enabled("sessions")) return [];
  const wanted = new Set(refKeys);
  const [recent, older] = yield* Effect.all([logFiles(RECENT_DAYS), logFiles(MENTION_DAYS)], {
    concurrency: "unbounded",
  });
  const matched = wanted.size
    ? (yield* Effect.forEach(
        older,
        (file) =>
          part(file).pipe(
            Effect.map((found) =>
              found && [...Object.keys(found.refs), ...(found.linkedPRs ?? [])].some((key) => wanted.has(key))
                ? [file]
                : [],
            ),
            Effect.orElseSucceed((): string[] => []),
          ),
        { concurrency: 2 },
      )).flat()
    : [];
  const now = yield* Clock.currentTimeMillis;
  const files = yield* expandClaudeFiles([...new Set([...recent, ...matched])], yield* claudeFiles);
  return yield* sessionsFrom(files, now - MENTION_DAYS * DAY);
});
