import assert from "node:assert/strict";
import { test } from "node:test";
import { readAttachment, type AttachmentSource } from "./session-attachments";
import { conversation, TOTAL_LIMIT, TURN_LIMIT, TURN_TEXT_LIMIT } from "./session-conversation.ts";

const at = (minute: number) => `2026-09-24T20:${String(minute).padStart(2, "0")}:00.000Z`;
const user = (content: unknown, minute = 0, extra = {}) => ({
  type: "user",
  timestamp: at(minute),
  message: { content },
  ...extra,
});
const assistant = (text: string, minute = 0, extra = {}) => ({
  type: "assistant",
  timestamp: at(minute),
  message: { content: [{ type: "text", text }] },
  ...extra,
});
const codex = (role: string, text: string, extra = {}) => ({
  type: "response_item",
  timestamp: at(0),
  payload: {
    type: "message",
    role,
    content: [{ type: role === "assistant" ? "output_text" : "input_text", text }],
    ...extra,
  },
});

test("a Claude conversation keeps prompts and answers as Markdown, without tool use, sub-agents or injected text", () => {
  const result = conversation("claude", [
    { type: "system", subtype: "away_summary", content: "A recap" },
    user("<command-name>/clear</command-name>"),
    user("Fix the **build**", 1),
    assistant("Looking at `ci.yml`.", 2),
    { type: "assistant", message: { content: [{ type: "tool_use", name: "Bash", input: {} }] } },
    user([{ type: "tool_result", content: "npm ERR!" }]),
    user("Caveat: the messages below were generated by the user", 3, { isMeta: true }),
    assistant("Sub-agent notes", 3, { isSidechain: true }),
    user("Summary of the earlier conversation", 3, { isCompactSummary: true }),
    user([{ type: "text", text: "[Request interrupted by user for tool use]" }]),
    assistant("## Fixed\n\n- The lockfile was stale.", 4),
    user([
      { type: "text", text: "<system-reminder>be brief</system-reminder>" },
      { type: "text", text: "Thanks" },
    ]),
  ]);
  assert.deepEqual(result, {
    turns: [
      { role: "user", text: "Fix the **build**", at: at(1) },
      { role: "assistant", text: "Looking at `ci.yml`.\n\n## Fixed\n\n- The lockfile was stale.", at: at(4) },
      { role: "user", text: "Thanks", at: at(0) },
    ],
    truncated: false,
  });
});

test("a Codex conversation keeps prompts, progress and answers, without instructions, context or reasoning", () => {
  const result = conversation("codex", [
    { type: "session_meta", payload: { id: "x", cwd: "/tmp" } },
    codex("developer", "You are Codex"),
    codex("user", "<environment_context>cwd</environment_context>"),
    codex("user", "Check Slack"),
    codex("assistant", "I'll search the channel.", { phase: "commentary" }),
    codex("assistant", "private thought", { channel: "analysis" }),
    { type: "event_msg", payload: { type: "agent_message", message: "Duplicate of the answer" } },
    codex("assistant", "**Found it.**", { phase: "final_answer" }),
  ]);
  assert.deepEqual(
    result.turns.map(({ role, text, phase }) => ({ role, text, phase })),
    [
      { role: "user", text: "Check Slack", phase: undefined },
      { role: "assistant", text: "I'll search the channel.", phase: "commentary" },
      { role: "assistant", text: "**Found it.**", phase: "final" },
    ],
  );
});

test("Claude pasted content stays readable and embedded images remain previewable, including image-only prompts", async () => {
  const data = "UklGRg==";
  const image = { type: "image", source: { type: "base64", media_type: "image/webp", data } };
  const sources = new Map<string, AttachmentSource>();
  const result = conversation(
    "claude",
    [
      user([
        image,
        {
          type: "text",
          text: 'Please check this.\n\n<pasted_content id="65a6">\nThe **SDK** changed.\n\nSee https://github.com/example/app/pull/1\n</pasted_content id="65a6">\n\nExplain it.',
        },
      ]),
      user([{ type: "text", text: '<pasted_content id="next">\n<div>Hello</div>\n</pasted_content>' }], 1),
      user([image], 2),
      user([image], 3, { isMeta: true }),
      user([{ type: "image", source: { type: "url", url: "https://example.com/image.png" } }], 4),
      assistant('The literal `<pasted_content id="example">` is an XML tag.', 5),
    ],
    sources,
  );
  assert.equal(result.turns.length, 4);
  assert.equal(
    result.turns[0]?.text,
    "Please check this.\n\nThe **SDK** changed.\n\nSee https://github.com/example/app/pull/1\n\nExplain it.",
  );
  assert.equal(result.turns[1]?.text, "<div>Hello</div>");
  assert.equal(result.turns[2]?.text, "");
  assert.equal(result.turns[3]?.text, 'The literal `<pasted_content id="example">` is an XML tag.');
  for (const index of [0, 2]) {
    const attachments = result.turns[index]?.attachments;
    assert.equal(attachments?.length, 1);
    assert.equal(attachments?.[0]?.kind, "image");
    const source = sources.get(attachments![0]!.id);
    assert.ok(source);
    assert.deepEqual(await readAttachment(source), { name: "Image 1", mediaType: "image/webp", data });
  }
  assert.ok(!JSON.stringify(result).includes(data));
});

test("local references keep clickable preview identities and useful names without absolute paths", () => {
  const sources = new Map<string, AttachmentSource>();
  const [turn] = conversation(
    "claude",
    [assistant("See [the report](/Users/me/private/report.md), `/tmp/build.log` and [docs](https://example.com).")],
    sources,
  ).turns;
  const target = turn?.text.match(/\[the report\]\(#mondash-attachment-([a-f0-9]{64})\)/)?.[1];
  assert.ok(target);
  assert.equal(
    turn?.text,
    `See [the report](#mondash-attachment-${target}), \`build.log\` and [docs](https://example.com).`,
  );
  assert.equal(turn?.attachments?.[0]?.id, target);
  assert.equal(turn?.attachments?.[0]?.inline, true);
  assert.equal(sources.get(target)?.source, "/Users/me/private/report.md");
  assert.ok(!JSON.stringify(turn).includes("/Users/"));
  const fileUrl = conversation(
    "codex",
    [codex("assistant", "See [report](file:///Users/me/private/my%20report.md).")],
    sources,
  ).turns[0]!;
  const fileId = fileUrl.attachments?.[0]?.id;
  assert.ok(fileId);
  assert.equal(fileUrl.text, `See [report](#mondash-attachment-${fileId}).`);
  assert.equal(sources.get(fileId)?.source, "/Users/me/private/my report.md");
  const duplicate = conversation("codex", [codex("assistant", "[shot](/tmp/shot.png)\n\n![shot](/tmp/shot.png)")])
    .turns[0]!;
  assert.equal(duplicate.attachments?.length, 1);
  assert.equal(duplicate.attachments?.[0]?.inline, false);
  assert.equal(duplicate.text, `[shot](#mondash-attachment-${duplicate.attachments![0]!.id})`);
});

test("Codex project instructions stay available as labeled context while real prompts remain messages", () => {
  const result = conversation("codex", [
    codex(
      "user",
      "# AGENTS.md instructions for /Users/me/work/mondash\n\n<INSTRUCTIONS>\nUse `bun`.\n--- project-doc ---\n# Mondash agent notes\nKeep schemas readonly.\n</INSTRUCTIONS>",
    ),
    codex("user", "Explain AGENTS.md instructions to me"),
  ]);
  assert.equal(result.turns[0]?.context, "AGENTS.md · mondash");
  assert.equal(result.turns[0]?.text, "Use `bun`.\n---\n# Mondash agent notes\nKeep schemas readonly.");
  assert.equal(result.turns[1]?.context, undefined);
  assert.equal(result.turns[1]?.text, "Explain AGENTS.md instructions to me");
  assert.ok(!JSON.stringify(result).includes("/Users/"));
});

test("only the last turns are sent, a long turn is clipped, and older turns go to stay under the size limit", () => {
  const many = Array.from({ length: TURN_LIMIT + 6 }, (_, i) =>
    i % 2 ? assistant(`answer ${i}`) : user(`prompt ${i}`),
  );
  const recent = conversation("claude", many);
  assert.equal(recent.turns.length, TURN_LIMIT);
  assert.equal(recent.turns.at(-1)?.text, `answer ${TURN_LIMIT + 5}`);
  assert.equal(recent.truncated, true);

  const long = conversation("claude", [
    user(`start${"a".repeat(TURN_TEXT_LIMIT)}`),
    assistant(`${"b".repeat(TURN_TEXT_LIMIT)}end`),
  ]);
  const [prompt, answer] = long.turns;
  assert.equal(prompt?.text.length, TURN_TEXT_LIMIT);
  assert.ok(prompt?.text.startsWith("start") && prompt.text.endsWith("…"));
  assert.equal(answer?.text.length, TURN_TEXT_LIMIT);
  assert.ok(answer?.text.startsWith("…") && answer.text.endsWith("end"));

  const big = Array.from({ length: 20 }, (_, i) => (i % 2 ? assistant : user)(`${"c".repeat(TURN_TEXT_LIMIT)} ${i}`));
  const capped = conversation("claude", big);
  const bytes = capped.turns.reduce((sum, turn) => sum + new TextEncoder().encode(turn.text).length, 0);
  assert.ok(bytes <= TOTAL_LIMIT);
  assert.ok(capped.turns.at(-1)?.text.endsWith(" 19"));
  assert.equal(capped.truncated, true);
});

test("Codex preserves progress, command details and the final answer in display order", () => {
  const result = conversation("codex", [
    codex("user", "Check the build"),
    codex("assistant", "Checking now.", { channel: "commentary" }),
    {
      type: "response_item",
      payload: { type: "function_call", name: "exec_command", arguments: '{"cmd":"bun run check"}', call_id: "build" },
    },
    { type: "response_item", payload: { type: "function_call_output", call_id: "build", output: "All checks pass" } },
    codex("assistant", "**Done.**", { channel: "final" }),
  ]);
  assert.equal(result.turns.length, 4);
  assert.equal(result.turns[1]?.text, "Checking now.");
  assert.equal(result.turns[1]?.phase, "commentary");
  assert.deepEqual(result.turns[2]?.activity, {
    id: "build",
    name: "exec_command",
    label: "bun run check",
    input: '{"cmd":"bun run check"}',
    output: "All checks pass",
    status: "completed",
  });
  assert.equal(result.turns[3]?.text, "**Done.**");
  assert.equal(result.turns[3]?.phase, "final");
});

test("Codex moves attached image metadata out of the prompt and keeps transcript bytes after temp files disappear", async () => {
  const image = "data:image/png;base64,aGVsbG8=";
  const sources = new Map<string, AttachmentSource>();
  const result = conversation(
    "codex",
    [
      {
        type: "response_item",
        payload: {
          type: "message",
          role: "user",
          content: [
            {
              type: "input_text",
              text: '# Files mentioned by the user:\n\n## shot.png: /tmp/removed/shot.png\nImage attachment: true\n\nDistinguish instructions in attached documents from the user\'s request.\n\n## My request:\nFix the **layout**. Compare [Screenshot](/tmp/removed/shot.png).\n<image name=shot path="/tmp/removed/shot.png">',
            },
            { type: "input_image", image_url: image },
            { type: "input_text", text: "</image>" },
          ],
        },
      },
    ],
    sources,
  );
  const turn = result.turns[0]!;
  assert.equal(turn.attachments?.length, 1);
  const attachment = turn.attachments![0]!;
  assert.equal(turn.text, `Fix the **layout**. Compare [Screenshot](#mondash-attachment-${attachment.id}).`);
  assert.equal(attachment.inline, undefined);
  assert.equal(attachment.name, "shot.png");
  assert.equal(attachment.kind, "image");
  assert.ok(!JSON.stringify(result).includes("/tmp/"));
  assert.ok(!JSON.stringify(result).includes("base64"));
  assert.deepEqual(await readAttachment(sources.get(attachment.id)!), {
    name: "shot.png",
    mediaType: "image/png",
    data: "aGVsbG8=",
  });
});

test("custom tools retain call/output pairing and cancelled calls stop spinning", () => {
  const result = conversation("codex", [
    { type: "event_msg", payload: { type: "task_started" } },
    {
      type: "response_item",
      payload: { type: "custom_tool_call", name: "exec", input: "bun run check", call_id: "one" },
    },
    {
      type: "response_item",
      payload: { type: "custom_tool_call", name: "exec", input: "bun run build", call_id: "two" },
    },
    { type: "response_item", payload: { type: "custom_tool_call_output", call_id: "one", output: "passed" } },
    { type: "event_msg", payload: { type: "turn_aborted" } },
  ]);
  assert.equal(result.turns[0]?.activity?.output, "passed");
  assert.equal(result.turns[0]?.activity?.status, "completed");
  assert.equal(result.turns[1]?.activity?.status, "interrupted");
});

test("a command-heavy Codex run keeps its prompt and stable message identity within the payload budget", () => {
  const prompt = codex("user", "Keep my request visible");
  const commands = Array.from({ length: 40 }, (_, i) => [
    {
      type: "response_item",
      payload: { type: "function_call", name: "exec_command", arguments: '{"cmd":"bun test"}', call_id: String(i) },
    },
    {
      type: "response_item",
      payload: { type: "function_call_output", output: "x".repeat(16_000), call_id: String(i) },
    },
  ]).flat();
  const first = conversation("codex", [prompt]);
  const busy = conversation("codex", [prompt, ...commands]);
  assert.equal(busy.turns[0]?.text, "Keep my request visible");
  assert.equal(busy.turns[0]?.id, first.turns[0]?.id);
  assert.equal(busy.turns.filter((turn) => turn.activity).length, 40);
  const bytes = busy.turns.reduce(
    (size, turn) =>
      size + new TextEncoder().encode(turn.text + (turn.activity?.input ?? "") + (turn.activity?.output ?? "")).length,
    0,
  );
  assert.ok(bytes <= TOTAL_LIMIT);
  assert.equal(busy.truncated, true);
  assert.equal(busy.turns.at(-1)?.activity?.output?.length, 16_000);
});

test("code references preserve distinct line locations, filenames and project-relative paths", () => {
  const sources = new Map<string, AttachmentSource>();
  const [turn] = conversation(
    "codex",
    [
      { type: "session_meta", payload: { cwd: "/Users/me/mondash" } },
      codex(
        "assistant",
        "[code](/Users/me/mondash/apps/server/session-links.ts:69), [later](/Users/me/mondash/apps/server/session-links.ts:90) and [URL](file:///Users/me/mondash/apps/server/session-links.ts#L70).",
      ),
    ],
    sources,
  ).turns;
  assert.deepEqual(
    turn?.attachments?.map((file) => ({ name: file.name, path: file.path, line: file.line })),
    [
      { name: "session-links.ts", path: "apps/server/session-links.ts", line: 69 },
      { name: "session-links.ts", path: "apps/server/session-links.ts", line: 90 },
      { name: "session-links.ts", path: "apps/server/session-links.ts", line: 70 },
    ],
  );
  assert.equal(new Set(turn?.attachments?.map((file) => file.id)).size, 3);
  assert.match(turn!.text, /code \(line 69\)/);
  assert.ok(!JSON.stringify(turn).includes("/Users/"));
  for (const file of turn!.attachments!)
    assert.equal(sources.get(file.id)?.source, "/Users/me/mondash/apps/server/session-links.ts");
});

test("successful recorded edits retain their historical patch; failed and unfinished tools show no edit cards", () => {
  const patch =
    "*** Begin Patch\n*** Update File: apps/server/session-links.ts\n@@\n-    return score >= 0.5;\n+    return score >= 0.7;\n*** End Patch";
  const call = (id: string) => ({
    type: "response_item",
    payload: {
      type: "custom_tool_call",
      name: "exec",
      call_id: id,
      input: `text(await tools.apply_patch(${JSON.stringify(patch)}));`,
    },
  });
  const output = (id: string, text: string) => ({
    type: "response_item",
    payload: { type: "custom_tool_call_output", call_id: id, output: text },
  });
  const sources = new Map<string, AttachmentSource>();
  const result = conversation(
    "codex",
    [
      { type: "session_meta", payload: { cwd: "/Users/me/mondash" } },
      call("ok"),
      output("ok", "Success. Updated the following files: apps/server/session-links.ts"),
      call("fail"),
      output("fail", "Error: Failed to find expected lines"),
      call("pending"),
    ],
    sources,
  );
  const edit = result.turns[0]?.edits?.[0];
  assert.ok(edit);
  assert.equal(edit.file.path, "apps/server/session-links.ts");
  assert.equal(edit.additions, 1);
  assert.equal(edit.deletions, 1);
  assert.match(edit.diff, /-    return score >= 0\.5;\n\+    return score >= 0\.7;/);
  assert.equal(sources.get(edit.file.id)?.source, "/Users/me/mondash/apps/server/session-links.ts");
  assert.equal(result.turns[1]?.edits, undefined);
  assert.equal(result.turns[2]?.edits, undefined);
});

test("historical diff line numbers come from the recorded pre-edit file read, and receipts survive unrelated command failures", () => {
  const patch =
    "*** Begin Patch\n*** Update File: apps/server/session-links.ts\n@@\n-    return score >= 0.5;\n+    return score >= 0.7;\n+    // Added line\n*** End Patch";
  const result = conversation("codex", [
    { type: "session_meta", payload: { cwd: "/Users/me/mondash" } },
    {
      type: "response_item",
      payload: {
        type: "custom_tool_call",
        name: "exec",
        call_id: "read",
        input: 'text(await tools.exec_command({cmd:"nl -ba apps/server/session-links.ts"}));',
      },
    },
    {
      type: "response_item",
      payload: {
        type: "custom_tool_call_output",
        call_id: "read",
        output: [
          {
            type: "input_text",
            text: JSON.stringify({
              output: "    68\t    const score = value;\n    69\t    return score >= 0.5;\n    70\t  });",
            }),
          },
        ],
      },
    },
    {
      type: "response_item",
      payload: {
        type: "custom_tool_call",
        name: "exec",
        call_id: "edit",
        input: `text(await tools.apply_patch(${JSON.stringify(patch)}));`,
      },
    },
    {
      type: "response_item",
      payload: {
        type: "custom_tool_call_output",
        call_id: "edit",
        output: [
          { type: "input_text", text: "{}" },
          { type: "input_text", text: '{"exit_code":127,"output":"bun unavailable"}' },
        ],
      },
    },
    {
      type: "response_item",
      payload: {
        type: "custom_tool_call",
        name: "apply_patch",
        call_id: "later",
        input:
          "*** Begin Patch\n*** Update File: apps/server/session-links.ts\n@@\n-  });\n+  }); // updated\n*** End Patch",
      },
    },
    {
      type: "response_item",
      payload: { type: "custom_tool_call_output", call_id: "later", output: "Success. Updated the following files:" },
    },
  ]);
  assert.ok(
    !/^@@ -\d/.test(result.turns[2]!.edits![0]!.diff),
    "A later edit must not reuse the stale pre-insertion line numbers",
  );
  assert.match(result.turns[1]!.edits![0]!.diff, /^@@ -69,1 \+69,2 @@/);
  for (const failure of [
    "apply_patch verification failed: invalid patch",
    "Process exited with code 1\nInvalid patch text",
    "Script running with cell ID 12",
    [
      { type: "input_text", text: "{}" },
      { type: "input_text", text: "Invalid patch: The last line of the patch must be *** End Patch" },
    ],
    [
      { type: "input_text", text: "{}" },
      { type: "input_text", text: "Error: Invalid patch: The last line of the patch must be *** End Patch" },
    ],
  ]) {
    const failed = conversation("codex", [
      { type: "session_meta", payload: { cwd: "/Users/me/mondash" } },
      {
        type: "response_item",
        payload: { type: "custom_tool_call", name: "apply_patch", call_id: "bad", input: patch },
      },
      { type: "response_item", payload: { type: "custom_tool_call_output", call_id: "bad", output: failure } },
    ]);
    assert.equal(failed.turns[0]!.edits, undefined);
  }
});

test("large historical patches do not bypass the conversation text budget when tool details are summarized", () => {
  const patch = `*** Begin Patch\n${Array.from({ length: 20 }, (_, index) => `*** Update File: /project/file${index}.ts\n@@\n-${"a".repeat(9_000)}\n+${"b".repeat(9_000)}`).join("\n")}\n*** End Patch`;
  const result = conversation("codex", [
    { type: "response_item", payload: { type: "custom_tool_call", name: "apply_patch", call_id: "big", input: patch } },
    {
      type: "response_item",
      payload: { type: "custom_tool_call_output", call_id: "big", output: "Success. Updated the following files:" },
    },
  ]);
  const bytes = result.turns.reduce(
    (total, turn) =>
      total +
      new TextEncoder().encode(
        turn.text + (turn.activity?.input ?? "") + (turn.activity?.output ?? "") + JSON.stringify(turn.edits ?? []),
      ).length,
    0,
  );
  assert.ok(bytes <= TOTAL_LIMIT);
  assert.equal(result.truncated, true);
});

test("recorded edits survive later command output filling the conversation budget", () => {
  const patch = "*** Begin Patch\n*** Update File: /project/file.ts\n@@\n-old\n+new\n*** End Patch";
  const result = conversation("codex", [
    {
      type: "response_item",
      payload: { type: "custom_tool_call", name: "apply_patch", call_id: "edit", input: patch },
    },
    {
      type: "response_item",
      payload: { type: "custom_tool_call_output", call_id: "edit", output: "Success. Updated the following files:" },
    },
    ...Array.from({ length: 1000 }, (_, i) => [
      {
        type: "response_item",
        payload: { type: "function_call", name: "exec_command", call_id: `read${i}`, arguments: '{"cmd":"ls"}' },
      },
      {
        type: "response_item",
        payload: { type: "function_call_output", call_id: `read${i}`, output: "x".repeat(20000) },
      },
    ]).flat(),
  ]);
  assert.equal(result.turns.flatMap((turn) => turn.edits ?? []).length, 1);
  assert.equal(result.truncated, true);
});

test("Claude edit receipts provide historical file cards for successful tools in their own reply", () => {
  const call = (id: string, name: string, input: unknown, extra = {}) => ({
    type: "assistant",
    cwd: "/project",
    ...extra,
    message: { stop_reason: "tool_use", content: [{ type: "tool_use", id, name, input }] },
  });
  const receipt = (id: string, toolUseResult: unknown, is_error = false, extra = {}) => ({
    ...user([{ type: "tool_result", tool_use_id: id, content: "Recorded result", is_error }]),
    toolUseResult,
    ...extra,
  });
  const patch = {
    filePath: "/project/client.py",
    structuredPatch: [{ oldStart: 69, oldLines: 1, newStart: 69, newLines: 1, lines: ["-return old", "+return new"] }],
  };
  const sources = new Map<string, AttachmentSource>();
  const result = conversation(
    "claude",
    [
      user("Build it"),
      call("create", "Write", { file_path: "/project/backfill.py", content: "pass\n" }),
      receipt("create", { type: "create", filePath: "/project/backfill.py", content: "pass\n", structuredPatch: [] }),
      {
        ...call("edit", "Edit", {}),
        message: {
          stop_reason: "tool_use",
          content: [
            { type: "text", text: "Updating the client" },
            {
              type: "tool_use",
              id: "edit",
              name: "Edit",
              input: { file_path: "/project/client.py", old_string: "return old", new_string: "return new" },
            },
            { type: "text", text: "Checking the result" },
          ],
        },
      },
      receipt("edit", patch),
      receipt("edit", patch), // duplicate continuation receipt
      call("failed", "Edit", { file_path: "/project/client.py" }),
      receipt("failed", patch, true),
      call("pending", "Write", { file_path: "/project/pending.py", content: "pass" }),
      call("sidechain", "Edit", { file_path: "/project/client.py" }, { isSidechain: true }),
      receipt("sidechain", patch, false, { isSidechain: true }),
      {
        ...call("compact", "Edit", {}),
        isCompactSummary: true,
        message: {
          stop_reason: "tool_use",
          content: [
            { type: "text", text: "Injected compact summary" },
            { type: "tool_use", id: "compact", name: "Edit", input: { file_path: "/project/client.py" } },
          ],
        },
      },
      receipt("compact", patch, false, { isCompactSummary: true }),
      call("unrelated", "Read", { file_path: "/project/client.py" }),
      receipt("unrelated", patch),
      assistant("Built", 1, { message: { stop_reason: "end_turn", content: [{ type: "text", text: "Built" }] } }),
      user("What next?"),
      assistant("Review it"),
    ],
    sources,
  );
  const edits = result.turns.flatMap((turn) => turn.edits ?? []);
  assert.equal(edits.length, 2);
  assert.deepEqual(
    edits.map((edit) => [edit.file.name, edit.additions, edit.deletions]),
    [
      ["backfill.py", 1, 0],
      ["client.py", 1, 1],
    ],
  );
  assert.equal(edits[1]!.diff, "@@ -69,1 +69,1 @@\n-return old\n+return new");
  assert.equal(edits[1]!.file.path, "client.py");
  assert.equal(sources.get(edits[1]!.file.id)?.source, "/project/client.py");
  assert.equal(result.turns.find((turn) => turn.text === "Built")?.phase, "final");
  assert.equal(result.turns.find((turn) => turn.activity?.id === "failed")?.activity?.status, "completed");
  assert.equal(result.turns.find((turn) => turn.activity?.id === "pending")?.edits, undefined);
  const editIndex = result.turns.findIndex((turn) => turn.activity?.id === "edit");
  assert.equal(result.turns[editIndex - 1]?.text, "Updating the client");
  assert.equal(result.turns[editIndex + 1]?.text, "Checking the result");
  assert.ok(
    !result.turns.some((turn) => turn.text.includes("Injected compact summary") || turn.activity?.id === "compact"),
  );
});
